namespace AxiomOps.Compass.Gtp;

/// <summary>
/// One deliverable of a project's V2 certification requirements
/// (GET /api/v1/deliverables/gameProject/{gameProjectId}). The V2 system is the
/// only one compass exposes; `Requirement.IsRequirementMet` is the source of
/// truth (submission-status is unreliable and ignored).
/// </summary>
public sealed class GtpDeliverable
{
    public int DeliverableId { get; set; }
    public string? DeliverableType { get; set; }
    public int DeliverableTypeId { get; set; }
    public int SubmissionId { get; set; }
    public bool IsOptional { get; set; }
    public bool HasMarketRequirements { get; set; }
    public bool CanAutoGenerate { get; set; }

    /// <summary>Stage name: "Testing", "SignOff" or "Certification".</summary>
    public string? SubmissionName { get; set; }

    public List<GtpDeliverableFile>? Files { get; set; }
    public GtpDeliverableRequirement? Requirement { get; set; }
}

public sealed class GtpDeliverableFile
{
    public int DeliverableFileId { get; set; }
    public List<GtpDeliverableFileVersion>? FileVersions { get; set; }
}

public sealed class GtpDeliverableFileVersion
{
    public int DeliverableFileVersionId { get; set; }
    public long FileStreamId { get; set; }
    public int Version { get; set; }
    public string? FileName { get; set; }
    public DateTimeOffset? CreatedOn { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? CreatedByUserName { get; set; }
}

public sealed class GtpDeliverableRequirement
{
    public bool IsOptional { get; set; }
    public bool IsRequirementMet { get; set; }
    public List<GtpGamingSystemRequirement>? GamingSystemRequirements { get; set; }
}

public sealed class GtpGamingSystemRequirement
{
    public int GamingSystemId { get; set; }
    public string? GamingSystemName { get; set; }
    public bool IsRequirementMet { get; set; }
    public List<GtpPayoutVariantRequirement>? PayoutVariantRequirements { get; set; }
}

public sealed class GtpPayoutVariantRequirement
{
    public int PayoutVariantId { get; set; }
    public string? PayoutShortName { get; set; }
    public bool IsRequirementMet { get; set; }
    public List<GtpMarketRequirement>? MarketRequirements { get; set; }
}

public sealed class GtpMarketRequirement
{
    public int MarketId { get; set; }
    public string? MarketLabel { get; set; }
    public bool IsRequirementMet { get; set; }
}
